export { Login } from "./Login";
export { UserRegister } from "./UserRegister";
export { CustomerHome } from "./CustomerHome";
export { CreateOrEditAppointment } from "./CreateOrEditAppointment";
export { HomePage } from "./HomePage";
export { ServicesPage } from "./ServicesPage";
export { ProfessionalsPage } from "./ProfessionalsPage";
export { ServiceRegister } from "./ServiceRegister";
export { ServiceEdit } from "./ServiceEdit";
